name = "OodiCore"
uuid = "7c15cd61-9c6a-4671-bc94-9960963998ac"
authors = ["Jukka Aho <jukka.aho@vtt.fi>"]
version = "0.1.0"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
